import { CategoryOrGroup } from './types'

export const seeds: CategoryOrGroup[] = [
	{
		id: 1,
		type: 'country',
		order: 1,
		name: 'USA Giftcards',
		name_fr: 'Cartes Cadeaux USA',
		name_ar: 'بطاقات الهدايا الولايات المتحدة',
		description: 'Giftcards for US stores',
		description_fr: 'Cartes cadeaux pour les magasins américains',
		description_ar: 'بطاقات هدايا للمتاجر الأمريكية',
		image_path: '/images/usa.png',
		small_image: '/images/usa_small.png',
		desclaimer: 'Only valid in USA',
		desclaimer_fr: 'Valide uniquement aux États-Unis',
		desclaimer_ar: 'صالحة فقط في الولايات المتحدة',
		in_stock: 1,
		giftcards: [
			{
				id: 101,
				name: 'Amazon USA $50',
				output: 'Amazon Code',
				output_fr: 'Code Amazon',
				output_ar: 'رمز أمازون',
				amount: '50',
				amount_after_fee: '48',
				in_stock: 1,
				country: 'US',
				category_id: 1,
				display_type: 'currency',
				display_value: '$',
				display_order: 1,
			},
		],
	},
	{
		id: 2,
		type: 'none',
		order: 2,
		name: 'Global Games',
		name_fr: 'Jeux Mondiaux',
		name_ar: 'ألعاب عالمية',
		description: 'Game giftcards',
		description_fr: 'Cartes cadeaux pour jeux',
		description_ar: 'بطاقات هدايا للألعاب',
		image_path: '/images/games.png',
		small_image: null,
		desclaimer: null,
		desclaimer_fr: null,
		desclaimer_ar: null,
		in_stock: 1,
		giftcards: [
			{
				id: 102,
				name: 'Steam Global $20',
				output: 'Steam Code',
				output_fr: 'Code Steam',
				output_ar: 'رمز ستيم',
				amount: '20',
				amount_after_fee: '19',
				in_stock: 1,
				country: null,
				category_id: 2,
				display_type: 'currency',
				display_value: '$',
				display_order: 1,
			},
		],
	},
	{
		id: 3,
		type: 'group',
		order: 1,
		name: 'Streaming Services',
		name_fr: 'Services de streaming',
		name_ar: 'خدمات البث',
		image_path: '/images/streaming.png',
		categories: [
			{
				id: 4,
				type: 'none',
				order: 1,
				name: 'Netflix',
				name_fr: 'Netflix',
				name_ar: 'نتفليكس',
				description: 'Netflix giftcards',
				description_fr: 'Cartes cadeaux Netflix',
				description_ar: 'بطاقات هدايا نتفليكس',
				image_path: '/images/netflix.png',
				small_image: null,
				desclaimer: 'Works worldwide',
				desclaimer_fr: 'Fonctionne dans le monde entier',
				desclaimer_ar: 'صالح في جميع أنحاء العالم',
				in_stock: 1,
				giftcards: [
					{
						id: 103,
						name: 'Netflix $15',
						output: 'Netflix Code',
						output_fr: 'Code Netflix',
						output_ar: 'رمز نتفليكس',
						amount: '15',
						amount_after_fee: '14',
						in_stock: 1,
						country: null,
						category_id: 4,
						display_type: 'currency',
						display_value: '$',
						display_order: 1,
					},
				],
			},
		],
	},
	{
		id: 5,
		type: 'country',
		order: 3,
		name: 'UK Giftcards',
		name_fr: 'Cartes Cadeaux Royaume-Uni',
		name_ar: 'بطاقات هدايا المملكة المتحدة',
		description: 'Giftcards for UK stores',
		description_fr: 'Cartes cadeaux pour les magasins britanniques',
		description_ar: 'بطاقات هدايا للمتاجر البريطانية',
		image_path: '/images/uk.png',
		small_image: null,
		desclaimer: 'Only valid in UK',
		desclaimer_fr: 'Valide uniquement au Royaume-Uni',
		desclaimer_ar: 'صالحة فقط في المملكة المتحدة',
		in_stock: 1,
		giftcards: [],
	},
	{
		id: 6,
		type: 'none',
		order: 4,
		name: 'PlayStation',
		name_fr: 'PlayStation',
		name_ar: 'بلايستيشن',
		description: 'PSN Giftcards',
		description_fr: 'Cartes cadeaux PSN',
		description_ar: 'بطاقات هدايا PSN',
		image_path: '/images/ps.png',
		small_image: null,
		desclaimer: null,
		desclaimer_fr: null,
		desclaimer_ar: null,
		in_stock: 1,
		giftcards: [],
	},
	{
		id: 7,
		type: 'group',
		order: 2,
		name: 'Food Delivery',
		name_fr: 'Livraison de nourriture',
		name_ar: 'توصيل الطعام',
		image_path: '/images/food.png',
		categories: [],
	},
	{
		id: 8,
		type: 'country',
		order: 5,
		name: 'France Giftcards',
		name_fr: 'Cartes Cadeaux France',
		name_ar: 'بطاقات هدايا فرنسا',
		description: 'French giftcards',
		description_fr: 'Cartes cadeaux françaises',
		description_ar: 'بطاقات هدايا فرنسية',
		image_path: '/images/fr.png',
		small_image: null,
		desclaimer: null,
		desclaimer_fr: null,
		desclaimer_ar: null,
		in_stock: 1,
		giftcards: [],
	},
	{
		id: 9,
		type: 'none',
		order: 6,
		name: 'Xbox',
		name_fr: 'Xbox',
		name_ar: 'إكس بوكس',
		description: 'Xbox Giftcards',
		description_fr: 'Cartes cadeaux Xbox',
		description_ar: 'بطاقات هدايا إكس بوكس',
		image_path: '/images/xbox.png',
		small_image: null,
		desclaimer: null,
		desclaimer_fr: null,
		desclaimer_ar: null,
		in_stock: 1,
		giftcards: [],
	},
	{
		id: 10,
		type: 'group',
		order: 3,
		name: 'E-commerce Stores',
		name_fr: 'Magasins en ligne',
		name_ar: 'متاجر إلكترونية',
		image_path: '/images/ecommerce.png',
		categories: [],
	},
]
